<a href="https://colab.research.google.com/github/VitorGama10/PandasBasico.ipynb/blob/main/PythonInicio_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# trabalhando com arrays Numpy


In [2]:
import numpy as np 

km = np.loadtxt('carros-km.txt')

km

anos = np.loadtxt('carros-anos.txt', dtype = int)
anos


array([2003, 1991, 1990, 2019, 2006, 2012, 2019, 2009, 2010, 2011, 2002,
       2007, 2001, 2019, 2009, 2016, 2012, 2019, 2016, 2017, 2002, 2019,
       1994, 1991, 2019, 2019, 2016, 2019, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2019, 2019, 2009, 2019, 2013, 2003, 2019, 2002,
       2019, 2002, 2004, 2001, 2019, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2019, 2019, 2019, 2019, 2019, 2017, 2011, 2001, 1996,
       2019, 1994, 2019, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2019, 2019, 1999, 2007, 1993, 1995, 2019, 2019, 2016, 2011,
       2019, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2019, 2006, 2001, 2019, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2019, 2017, 2019, 2019, 2006, 2015, 2007,
       2005, 2017, 1998, 2019, 1999, 2019, 2009, 2003, 1994, 2019, 1994,
       2019, 2015, 1996, 1997, 1993, 2019, 1992, 1995, 2019, 1990, 2019,
       2019, 1991, 1990, 2012, 2007, 2013, 2000, 20

 # Obtendo a quilometragem media por ano

In [3]:
km_media = km / (2019 - anos)
km 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
       1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
       1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
       1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
       1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
       0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
       3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
       4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
       9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
       9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
       8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
       8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
       9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00000e+00, 2.913

# Decleração de variaveis
Operadores de atribuição

In [4]:
ano_atual = 2019
ano_fabricaçao= 2003
km_total = 44410.0

In [5]:
ano_atual 

2019

In [6]:
ano_fabricaçao 

2003

In [7]:
km_total 

44410.0

In [8]:
km_media = km_total / (ano_atual - ano_fabricaçao) 
km_media

2775.625

In [9]:
ano_atual = 2019 
ano_fabricaçao = 2003
km_total = 44410.0
km_media = km_total / (ano_atual - ano_fabricaçao)
km_total = km_total + km_media 
km_total 

47185.625

In [10]:
ano_atual = 2019 
ano_fabricaçao = 2003
km_total = 44410.0
km_media = km_total / (ano_atual - ano_fabricaçao)
km_total += km_media 
km_total 

47185.625

conclusão

In [11]:
# "valor = valor + 1 é igual a "valor += 1 "

# conversão de tipos

In [12]:
a = 10 
b = 20 
c = "python é"
d = 'legal'

In [13]:
type(a)

int

In [14]:
type(c)

str

In [15]:
str(a)

'10'

In [16]:
type((a))

int

In [17]:
c + str(a)

'python é10'


# f-Strings
---



In [18]:
nome = 'Rodrigo'
acessos = 32 

In [19]:
print(f'ola, {nome}! Este é seu acesso de numero {acessos}')

ola, Rodrigo! Este é seu acesso de numero 32


#Criando listas


In [20]:
Acessorios = ['Rodas de liga', 'Travas eletricas', 'Piloto automatico', 'Banco de couro', 'Ar condicionado', 'Sensor de estabelecimento', 'Sensor crepuscular', 'sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas eletricas',
 'Piloto automatico',
 'Banco de couro',
 'Ar condicionado',
 'Sensor de estabelecimento',
 'Sensor crepuscular',
 'sensor de chuva']

#lista com tipos de dados variados


In [21]:
Carros_1 = ['jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas eletricas', 'Piloto automatico'], 88078.64]
Carros_2 = ['Passat', 'Motor Diesel', 1991, 5712, 5712.0, False, ['Central multimidia', 'Teto panoramico', 'Freios ABS'], 106161.94]

In [22]:
Carros_1

['jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas eletricas', 'Piloto automatico'],
 88078.64]

In [23]:
Carros_2

['Passat',
 'Motor Diesel',
 1991,
 5712,
 5712.0,
 False,
 ['Central multimidia', 'Teto panoramico', 'Freios ABS'],
 106161.94]

In [24]:
Carros = [Carros_1, Carros_2]
Carros

[['jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas eletricas', 'Piloto automatico'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712,
  5712.0,
  False,
  ['Central multimidia', 'Teto panoramico', 'Freios ABS'],
  106161.94]]

#3.2 Operaçoes com lista

https://docs.python.org/3.6/library/stdypes.html#common-sequence-operations

x in A 
Retorna True se um elemento de lista A for igual a x


In [25]:
Acessorios

['Rodas de liga',
 'Travas eletricas',
 'Piloto automatico',
 'Banco de couro',
 'Ar condicionado',
 'Sensor de estabelecimento',
 'Sensor crepuscular',
 'sensor de chuva']

In [26]:
'Rodas de liga' in Acessorios

True

In [27]:
'feat' in Acessorios

False

In [28]:
'Rodas de liga' not in Acessorios

False

In [29]:
'feat' not in Acessorios

True

#A + B
concatena as listas A e B

In [30]:
A = ['Rodas de liga', 'Travas eletricas', 'Piloto automatico', 'Bancos de couro']
B = ['Ar condicionado', 'Sensor de estabelecimento', 'Sensor de chuva']

In [31]:
A

['Rodas de liga', 'Travas eletricas', 'Piloto automatico', 'Bancos de couro']

In [32]:
B

['Ar condicionado', 'Sensor de estabelecimento', 'Sensor de chuva']

In [33]:
A + B

['Rodas de liga',
 'Travas eletricas',
 'Piloto automatico',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estabelecimento',
 'Sensor de chuva']

#len (A)
tamanho da lista A

In [34]:
len(Acessorios)

8

# A[i]
retorna o i-esimo item da lista 

In [35]:
Acessorios

['Rodas de liga',
 'Travas eletricas',
 'Piloto automatico',
 'Banco de couro',
 'Ar condicionado',
 'Sensor de estabelecimento',
 'Sensor crepuscular',
 'sensor de chuva']

In [36]:
Acessorios[0]

'Rodas de liga'

In [37]:
Acessorios[1]

'Travas eletricas'

In [38]:
Acessorios[-1]

'sensor de chuva'

In [39]:
Carros

[['jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas eletricas', 'Piloto automatico'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712,
  5712.0,
  False,
  ['Central multimidia', 'Teto panoramico', 'Freios ABS'],
  106161.94]]

In [40]:
 Carros[0]

['jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas eletricas', 'Piloto automatico'],
 88078.64]

In [41]:
Carros[0][0]

'jetta Variant'

In [42]:
Carros[0][-2]

['Rodas de liga', 'Travas eletricas', 'Piloto automatico']

In [43]:
Carros[0][-2][1]

'Travas eletricas'

In [44]:
Carros[0]

['jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas eletricas', 'Piloto automatico'],
 88078.64]

In [45]:
Carros

[['jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas eletricas', 'Piloto automatico'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712,
  5712.0,
  False,
  ['Central multimidia', 'Teto panoramico', 'Freios ABS'],
  106161.94]]

In [46]:
Carros [1][-2][1]

'Teto panoramico'

In [47]:
Carros[0][-2]

['Rodas de liga', 'Travas eletricas', 'Piloto automatico']

#A [i:j]
recorta a lista A do indice i ate o j. Neste fatiamento o elemento com indice i é incluindo e o elemento com indice j nao e incluindo no resultado.

In [48]:
Acessorios

['Rodas de liga',
 'Travas eletricas',
 'Piloto automatico',
 'Banco de couro',
 'Ar condicionado',
 'Sensor de estabelecimento',
 'Sensor crepuscular',
 'sensor de chuva']

In [49]:
Acessorios[2:6]

['Piloto automatico',
 'Banco de couro',
 'Ar condicionado',
 'Sensor de estabelecimento']

# 3.4 Metodos de lista
https://docs.python.org/3.6/library/stdypes.html#mutable-sequence-types

In [50]:
Acessorios = ['jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas eletricas', 'Piloto automatico'], 88078.64]

 # A.sort()
ordena a lista A

In [51]:
Acessorios.sort()

TypeError: ignored

#A.append(x)
adiciona o elemento x no final da lista a

In [52]:
Acessorios.append('4 x 4')
Acessorios

['jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas eletricas', 'Piloto automatico'],
 88078.64,
 '4 x 4']

# A.pop(i)
Remove e retorna o elemento de indice i da lista A

In [53]:
Acessorios.pop()

'4 x 4'

In [54]:
Acessorios

['jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas eletricas', 'Piloto automatico'],
 88078.64]

In [55]:
Acessorios.pop(4)

False

In [56]:
Acessorios

['jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 ['Rodas de liga', 'Travas eletricas', 'Piloto automatico'],
 88078.64]

#A.copy()
cria uma copia da lista A 

In [57]:
Acessorios_2 = Acessorios
Acessorios_2

['jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 ['Rodas de liga', 'Travas eletricas', 'Piloto automatico'],
 88078.64]

In [58]:
Acessorios_2.append('4 X 4')
Acessorios_2

['jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 ['Rodas de liga', 'Travas eletricas', 'Piloto automatico'],
 88078.64,
 '4 X 4']

In [59]:
Acessorios_2.pop()
Acessorios_2 

['jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 ['Rodas de liga', 'Travas eletricas', 'Piloto automatico'],
 88078.64]

In [60]:
Acessorios

['jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 ['Rodas de liga', 'Travas eletricas', 'Piloto automatico'],
 88078.64]

In [61]:
Acessorios_2

['jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 ['Rodas de liga', 'Travas eletricas', 'Piloto automatico'],
 88078.64]

#4.1 Instrução for 

In [62]:
Acessorios = ['jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas eletricas', 'Piloto automatico'], 88078.64]
Acessorios

['jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas eletricas', 'Piloto automatico'],
 88078.64]

In [63]:
for item in Acessorios:
  print(item)

jetta Variant
Motor 4.0 Turbo
2003
44410.0
False
['Rodas de liga', 'Travas eletricas', 'Piloto automatico']
88078.64


In [64]:
range(0, 10)

range(0, 10)

In [65]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [66]:
for i in range(10):
  print(i ** 2)

0
1
4
9
16
25
36
49
64
81


In [67]:
quadrado = []
for i in range(10):
  quadrado.append(i ** 2)
quadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

#4.2 Loops aninhados

In [68]:
 #dados = [
      #['Rodas de liga', 'Travas eletricas', 'Pilotos automatico', 'Bancos de dados', 'Ar condicionado', 'Sensor estabelimento' 'Sensor crepuscular', 'Sensor de chuva']
      #['Central multimidia', 'Teto paronamico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automatico', 'Bancos de couro', 'Camera de estabelecimento']
      #['Piloto automatico', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios Abs', 'Cambio automatico', 'Bancos de couro', 'Central multimidia', 'Vidros eletricos']
]
#dados

SyntaxError: ignored

In [69]:
for lista in dados: 
  print(lista)

NameError: ignored

# IF e FOR

In [70]:
dados = [
         ['jetta variant', 2003, False],
         ['passat', 1991, False],
         ['crossfox', 1990, False],
         ['Ds5', 2019, True],
         ['Aston martin db4', 2006, False],
         ['palio', 'weekend', 2012, False],
         ['A5', 2019, True],
         ['serie 3 cabrio', 2009, False],
         ['dodge', 2019, False],
         ['carens', 2011, False]
]
dados

[['jetta variant', 2003, False],
 ['passat', 1991, False],
 ['crossfox', 1990, False],
 ['Ds5', 2019, True],
 ['Aston martin db4', 2006, False],
 ['palio', 'weekend', 2012, False],
 ['A5', 2019, True],
 ['serie 3 cabrio', 2009, False],
 ['dodge', 2019, False],
 ['carens', 2011, False]]

# If e Else e Elif

In [71]:
for lista in dados: 
  if(lista[2] == True):
    print(lista)

['Ds5', 2019, True]
['A5', 2019, True]


In [ ]:
zero_km_y, zero_km_N = [], []
for lista in dados:
  if(lista[2] == True):
    zero_km_y.append(lista)
  else: 
    zero_km_N

In [ ]:
zero_km_y

[['Ds5', 2019, True], ['A5', 2019, True]]

In [ ]:
zero_km_N

[]

In [ ]:
A, B, C = [], [], []

for lista in dados:
  if( lista[1] <= 2000 ):
    A.append(lista)
  elif(lista[1] > 2000 and lista[1] <= 2010):
    B.append(lista)
  else:
    C.append(lista)

# Contas

In [72]:
dados

[['jetta variant', 2003, False],
 ['passat', 1991, False],
 ['crossfox', 1990, False],
 ['Ds5', 2019, True],
 ['Aston martin db4', 2006, False],
 ['palio', 'weekend', 2012, False],
 ['A5', 2019, True],
 ['serie 3 cabrio', 2009, False],
 ['dodge', 2019, False],
 ['carens', 2011, False]]

In [ ]:
import numpy as pd

In [ ]:
km = np.array([1000, 2300, 4987, 1500])
km

array([1000, 2300, 4987, 1500])

In [ ]:
km = np.array([44410, 5712, 37123,0, 25757])
anos = np.array([2003, 1991,1990,2019, 2006])
idade = 2019 - anos

In [ ]:
idade 

array([16, 28, 29,  0, 13])

In [ ]:
km_media = km/idade

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
km_media 

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

# selecionando cont[1:4]

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador[1:4]

array([1, 2, 3])

In [ ]:
contador[1:8:2]

array([1, 3, 5, 7])

In [ ]:
contador[::2]

array([0, 2, 4, 6, 8])

In [ ]:
contador[1::2]

array([1, 3, 5, 7, 9])

In [ ]:
km, anos 

(array([44410,  5712, 37123,     0, 25757]),
 array([2003, 1991, 1990, 2019, 2006]))

In [ ]:
kms = km, anos
kms

(array([44410,  5712, 37123,     0, 25757]),
 array([2003, 1991, 1990, 2019, 2006]))

In [ ]:
kms[0]

array([44410,  5712, 37123,     0, 25757])

# Atributos

In [ ]:
kms

(array([44410,  5712, 37123,     0, 25757]),
 array([2003, 1991, 1990, 2019, 2006]))

In [ ]:
kms.shape

AttributeError: ignored

In [ ]:
kms.size

AttributeError: ignored

# ndarray.T 
transforma em coluna

In [ ]:
kms.T

AttributeError: ignored

# metodos

In [ ]:
  kms = [44410,  5712, 37123,     0, 25757]
  anos = [2003, 1991, 1990, 2019, 2006]

In [ ]:
dados = kms, anos 
dados

([44410, 5712, 37123, 0, 25757], [2003, 1991, 1990, 2019, 2006])

In [ ]:
np.array(dados)

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [ ]:
dados

([44410, 5712, 37123, 0, 25757], [2003, 1991, 1990, 2019, 2006])

In [ ]:
dados.resize((3, 5), refcheck=False) #colocou uma nova coluna 

AttributeError: ignored

In [ ]:
dados[2] = dados [0] / (2019 - dados[1])

TypeError: ignored

# estatiticas com array numpy

In [ ]:
anos = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

In [ ]:
km 

array([4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
       1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
       1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
       1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
       1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
       0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
       3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
       4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
       9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
       9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
       8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
       8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
       9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00000e+00, 2.913

In [ ]:
km.mean()

44499.41472868217